import Link from "next/link";
import styles from "./home-sections.module.css";
import { SectionEyebrow } from "./site-shell";

export function HomeHero() {
  return <section className={styles.hero}><div className="wrap"><div className={styles.heroGrid}><div className={styles.heroCopy}><SectionEyebrow>Agent safety infrastructure · Arc testnet</SectionEyebrow><h1>Autonomy is<br /><em>earned.</em></h1><p>Repayd lets AI agents move with a spending boundary, a replayable decision trail, and recovery when something still slips through.</p><div className="actions"><Link className="button lime" href="/demo">Watch the live story ↗</Link><Link className={`button ${styles.outline}`} href="#how">See how it works ↓</Link></div><div className={styles.trust}><span className={styles.avatars}><i>A</i><i>G</i><i>R</i></span><span>Real testnet receipts.<br /><strong>Explicit trust boundaries.</strong></span></div></div><div className={styles.art}><div className={styles.grid} /><div className={`${styles.orbit} ${styles.orbitA}`} /><div className={`${styles.orbit} ${styles.orbitB}`} /><Shield /><Card className={styles.routine} label="ROUTINE PAYMENT" value="$180.00" note="Allowlisted · within policy" /><Card className={styles.block} label="POLICY BLOCK" value="$900.00" note="Reverted · no tokens moved" /><Card className={styles.recovery} label="RECOVERY RECEIPT" value="$135.00" note="Same-block payout · Arc testnet" /></div></div><div className={styles.heroFoot}><span>One protocol. Three lines of defense.</span><span>Scroll to explore ↓</span></div></div></section>;
}

function Shield() { return <svg className={styles.shield} viewBox="0 0 250 288" fill="none" aria-label="REPAYD safety shield"><path d="M125 8 228 44v83c0 65-42 119-103 150C64 246 22 192 22 127V44L125 8Z" fill="#d1fc70" stroke="#253312" strokeWidth="4"/><path d="M125 48 190 71v53c0 42-24 78-65 101-41-23-65-59-65-101V71l65-23Z" fill="#253312"/><path d="M125 82v91m-31-60 31-12 31 12" stroke="#d1fc70" strokeWidth="9" strokeLinecap="round" strokeLinejoin="round"/></svg>; }
function Card({ className, label, value, note }: { className: string; label: string; value: string; note: string }) { return <div className={`${styles.card} ${className}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>; }

export function HomePartners() { return <section className={styles.partners}><div className="wrap"><span>DESIGNED TO PLUG INTO<br />THE AGENT ECONOMY.</span><b>◒ Circle</b><b>◈ Arc</b><b>The Graph</b><b>◆ Hedera</b><b>ENS</b></div></section>; }

export function HomeHowItWorks() { const cards = [["01 / BOUNDARY", "Make the safe path the easy path.", "Policies are enforced at the account, not remembered in a prompt. Known recipients pass. Unknown destinations pause."], ["02 / EVIDENCE", "Replace “trust me” with “open the receipt.”", "Every action keeps its source, transaction, block, and reason. Chain evidence and local reasoning never blur together."], ["03 / RECOVERY", "Design for the moment prevention misses.", "A covered verdict calls a mutual pool and routes the payout back to the owner."]]; return <section id="how" className="wrap home-section"><div className="home-section-heading"><div><SectionEyebrow>The missing primitive</SectionEyebrow><h2>Your agent can be autonomous without being unaccountable.</h2></div><p>Wallets gave agents the ability to act. Repayd gives the people around them a reason to let them.</p></div><div className={styles.featureGrid}>{cards.map(([eyebrow,title,body]) => <article className={styles.feature} key={eyebrow}><span>{eyebrow}</span><h3>{title}</h3><p>{body}</p><div className={styles.featureMark} /></article>)}</div></section>; }

export function HomeStory() { return <section className="wrap home-section"><div className={styles.story}><div className={styles.storyCopy}><SectionEyebrow>The live story</SectionEyebrow><h2>Set the boundary before<br /><em>the first dollar moves.</em></h2><p>The agent can propose. It cannot decide alone. Follow one payment through policy, settlement, and proof.</p><div className="actions"><Link className="button lime" href="/app">Open policy workspace ↗</Link><Link className={`button ${styles.darkOutline}`} href="/flow">Read the receipt flow ↗</Link></div></div><div className={styles.trace}><div className={styles.traceTop}><span>DECISION TRACE · ARC TESTNET</span><b>ALLOWLISTED</b></div><div className={styles.traceRow}><div>Agent<small>PROPOSES</small></div><i /><div className={styles.guard}>Guard<small>ENFORCES</small></div><i /><div>World<small>SETTLES</small></div></div><div className={styles.traceTotal}><strong>$180.00</strong><span>POLICY PASS · 01/04</span></div><div className={styles.traceMeta}><span>per-transfer cap $200</span><span>daily count 1 / 5</span><span>recipient · Alice</span></div></div></div></section>; }

export function HomeProof() { return <section className="wrap home-section"><div className="home-section-heading"><div><SectionEyebrow>The proof layer</SectionEyebrow><h2>Numbers are useful.<br />Receipts are better.</h2></div><p>Real chain activity, clearly marked assumptions, and standard-registry mirrors.</p></div><div className={styles.proofGrid}><article className={styles.proofLime}><span>THE DEMO OUTCOME</span><strong>$135<small> covered</small></strong><h3>A same-block recovery for a controlled miss.</h3><p>Four routine payments, a frozen hold, a mined revert, a clean release, and a payout that closes the loop.</p><Link href="/demo">Open the live run ↗</Link></article><article className={styles.proofDark}><span>THE STANDARD MIRROR</span><strong>25<small> / 100</small></strong><h3>Verdict and reputation mirrored into ERC-8004.</h3><p>Agent 894341’s validation and covered feedback are indexed on The Graph alongside the protocol’s own risk data.</p><Link href="/record">Read the agent record ↗</Link></article></div></section>; }

export function HomeEcosystem() { const items = [["◈ ARC", "Settlement", "Policy and recovery contracts with explorer-ready receipts.", "/capital"], ["THE GRAPH", "Memory", "Risk state and ERC-8004 mirrors composed into one record.", "/flow"], ["◆ HEDERA", "Metering", "x402 access and HCS audit trails beyond one chain.", "/demo"], ["◎ ENS · CIRCLE", "Identity & wallets", "A discoverable agent résumé and managed wallet surface.", "/record"]]; return <section className="wrap home-section"><div className="home-section-heading"><div><SectionEyebrow>Designed as a control plane</SectionEyebrow><h2>One safety story.<br />Every surface accounted for.</h2></div><p>Circle, The Graph, Hedera, ENS, and Arc each support a different part of the control plane.</p></div><div className={styles.ecosystem}>{items.map(([label,title,body,href]) => <Link href={href} key={label}><span>{label}</span><h3>{title}</h3><p>{body}</p><b>Explore ↗</b></Link>)}</div></section>; }

export function HomeCta() { return <section className={`wrap ${styles.cta}`}><SectionEyebrow>A safer default for agent economies</SectionEyebrow><h2>Let intelligence move.<br />Give risk a boundary.</h2><p>Explore the live testnet story. No wallet connection required.</p><Link className="button dark-button" href="/demo">Start the live demo ↗</Link></section>; }
